services:
  gst-billing-mvp:
    build:
        context: .
        dockerfile: Dockerfile
    image: tykhegaming/gst-billing-mvp:latest
    container_name: gst-billing-mvp
    networks:
     - sas-network
    ports:
      - "9100:9100"
    restart: unless-stopped


networks:
  sas-network:
    external: true
    name: sas-network
